### ISSUE TITLE
Tree editing options

### ISSUE THREAD

**Issue by j-kominek** [cmzmasek/archaeopteryx-js#12]
Hi, ATV used to have two useful tree editing features that (to my knowledge) have been removed from Archeopteryx - Promote/Demote node and Multifurcate/Bifurcate. I wonder if there are any plans to bring those back? I am currently stuck with ATV 1.92 if I want to use them...thanks!

Cheers,
-Jacek

**Comment by cmzmasek** [comment]
Even though I am the main author of both ATV and Archeopteryx, I do not remember what these functions are. Could you explain in more detail?

**Comment by j-kominek** [comment]
Hi, thanks for the reply, and sure, no problem. Promote and Demote move a node (and all of its subnodes) either towards or away from the root on the tree. Multifurcate breaks a node in such a way, that it's two descendants are no longer sisters, but siblings with the branch one level up the tree, with Bifurcate forcing a multifurc'ed node to become bifurcating. Here's the JAR file with the app, hopefully directly testing it will offer a better explanation. Thanks for looking into it!

[eATVapp_1.1.0.jar.tar.gz](https://github.com/cmzmasek/archaeopteryx-js/files/1140248/eATVapp_1.1.0.jar.tar.gz)
